### ISSUE TITLE
embedding.pkl

### ISSUE THREAD

**Issue by maqbool11** [Raman-Raje/Machine-Reading-Comprehension-Neural-Question-Answer-#1]
running the cell, loading already stored embeding matrix and dictionary, gives an error No such file or directory: 'embedding.pkl'.
Where can we find this embedding.pkl

**Comment by Raman-Raje** [comment]
Sorry for the delay...

This file was computed seperately and then used to save the time.
you have to run the code for that one

**Comment by Raman-Raje** [comment]
Please let me know if you face any issue

**Comment by maqbool11** [comment]
ok thanks

**Comment by maqbool11** [comment]
Ok Thanks i already create embedding file thanks using glove vector dataset
embedding.pkl but i do not understand the use of  word2ix.pkl.and where and
how you create this file
Chaudhary Maqbool Alam
 Phd
Id No:I201722099
Huazhong university
 of science and
technology Wuhan

**Comment by Raman-Raje** [comment]
word2ix was created by using the dictionary of words. These are the same words that are used in embedding.

**Comment by Raman-Raje** [comment]
You can create your own one word 2 index dictionary

**Comment by maqbool11** [comment]
when i run this cell
d = pd.read_table("tags",delimiter = "|",header=None)

pos_tags_list = d[0].values
pos_tags_list = [et.strip() for et in pos_tags_list]
tag_to_num = {tag:i for i, tag in enumerate(sorted(pos_tags_list),1)}
num_to_tag = {i:tag for i, tag in enumerate(sorted(pos_tags_list),1)}

QUES_LEN = 40
CON_LEN = 680
TAGS = 36


print(len(pos_tags_list))

i find this error

FileNotFoundError                         Traceback (most recent call
last)<ipython-input-43-165cdd05cc70> in <module>----> 1 d =
pd.read_table("tags",delimiter = "|",header=None)      2       3
pos_tags_list = d[0].values      4 pos_tags_list = [et.strip() for et
in pos_tags_list]      5 tag_to_num = {tag:i for i, tag in
enumerate(sorted(pos_tags_list),1)}
~\Anaconda3\envs\Phd\lib\site-packages\pandas\io\parsers.py in
parser_f(filepath_or_buffer, sep, delimiter, header, names, index_col,
usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters,
true_values, false_values, skipinitialspace, skiprows, skipfooter,
nrows, na_values, keep_default_na, na_filter, verbose,
skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col,
date_parser, dayfirst, iterator, chunksize, compression, thousands,
decimal, lineterminator, quotechar, quoting, doublequote, escapechar,
comment, encoding, dialect, tupleize_cols, error_bad_lines,
warn_bad_lines, delim_whitespace, low_memory, memory_map,
float_precision)    700
skip_blank_lines=skip_blank_lines)    701 --> 702         return
_read(filepath_or_buffer, kwds)    703     704     parser_f.__name__ =
name
~\Anaconda3\envs\Phd\lib\site-packages\pandas\io\parsers.py in
_read(filepath_or_buffer, kwds)    427     428     # Create the
parser.--> 429     parser = TextFileReader(filepath_or_buffer, **kwds)
   430     431     if chunksize or iterator:
~\Anaconda3\envs\Phd\lib\site-packages\pandas\io\parsers.py in
__init__(self, f, engine, **kwds)    893
self.options['has_index_names'] = kwds['has_index_names']    894 -->
895         self._make_engine(self.engine)    896     897     def
close(self):
~\Anaconda3\envs\Phd\lib\site-packages\pandas\io\parsers.py in
_make_engine(self, engine)   1120     def _make_engine(self,
engine='c'):   1121         if engine == 'c':-> 1122
self._engine = CParserWrapper(self.f, **self.options)   1123
else:   1124             if engine == 'python':
~\Anaconda3\envs\Phd\lib\site-packages\pandas\io\parsers.py in
__init__(self, src, **kwds)   1851         kwds['usecols'] =
self.usecols   1852 -> 1853         self._reader =
parsers.TextReader(src, **kwds)   1854         self.unnamed_cols =
self._reader.unnamed_cols   1855
pandas/_libs/parsers.pyx in pandas._libs.parsers.TextReader.__cinit__()
pandas/_libs/parsers.pyx in
pandas._libs.parsers.TextReader._setup_parser_source()
FileNotFoundError: [Errno 2] File b'tags' does not exist: b'tags'





 i have already created embedding.pkl and word2ix.pkl
Chaudhary Maqbool Alam
 Phd
Id No:I201722099
Huazhong university
 of science and
technology Wuhan

**Comment by Raman-Raje** [comment]
Ohh...

The tags file you need to create.  This are standard POS tags.

**Comment by Raman-Raje** [comment]
https://drive.google.com/open?id=1PX-HhbIpOI-dtwJ0MO4PWrwqFE2BzoT4 you can get file from here

**Comment by maqbool11** [comment]
Thanks
Chaudhary Maqbool Alam
 Phd
Id No:I201722099
Huazhong university
 of science and
technology Wuhan

**Comment by maqbool11** [comment]
start_pred = []
end_pred = []
for i in range(10000):
    start_pred.append(np.argmax(y_[i,:CON_LEN]))
    end_pred.append(np.argmax(y_[i,CON_LEN:]))

start = []
end = []
for i in range(10000):
    start.append(np.argmax(y_dev[i,:CON_LEN]))
    end.append(np.argmax(y_dev[i,CON_LEN:]))
when i run this cell i will get error
i think that this code is not correct

TypeError                                 Traceback (most recent call
last)<ipython-input-116-44dd34099952> in <module>      8 end = []
9 for i in range(10000):---> 10
start.append(np.argmax(y_dev[i,:CON_LEN]))     11
end.append(np.argmax(y_dev[i,CON_LEN:]))
TypeError: list indices must be integers or slices, not tuple

Chaudhary Maqbool Alam
 Phd
Id No:I201722099
Huazhong university
 of science and
technology Wuhan

**Comment by bhavik1611** [comment]
I am having difficulty in training the embeddings, can you share your embeddings and word_2_ix?

**Comment by Azade0506** [comment]
could you please share your embedding.pkl file?

**Comment by omi982** [comment]
yes plz share your embedding.pkl FILE.
it will really help.
